const express = require('express');
const axios = require('axios');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 4000;

// Enable CORS for frontend communication
app.use(cors());
// List of services similar to TaskRabbit, including South Africa-specific services
const services = [
  'Plumber',
  'Electrician',
  'Carpenter',
  'Painter',
  'Cleaner',
  'Gardener',
  'Maid Service',
  'Tutor',
  'Babysitter',
  'Driver',
  'Chef',
  'Mechanic',
  'IT Support',
  'Photographer',
  'Dog Walker',
  'Furniture Assembly',
  'TV Mounting',
  'Packing & Unpacking',
  'Heavy Lifting',
  'Junk Removal',
  'Movers',
  'Household Repairs',
  'Wall Mounting',
  'Appliance Repair',
  'Air Conditioning Repair',
  'Handyman',
  'Pet Sitting',
  'Pet Grooming',
  'Home Organization',
  'Personal Shopper',
  'Errand Running',
  'Laundry Service',
  'Yard Work',
  'Snow Removal',
  'Cleaning Service',
  'Grocery Delivery',
  'Shopping Assistance',
  'Event Planning',
  'Party Setup',
  'Home Renovation',
  'Tiling',
  'Roof Repair',
  'Gardening',
  'Personal Assistant',
  'Hair Stylist',
  'Makeup Artist',
  'Massage Therapy',
  'Cleaning Services',
  'Window Washing',
  'House Sitting',
  'Fencing Services',
  'Roof Cleaning',
  'Window Repair',
  'Power Washing',
  'Pest Control',
  'Pool Cleaning',
  'Gutter Cleaning',
  'Painting & Wall Treatments',
  'Tree Removal',
  'Pool Table Assembly',
  'Playset Assembly',
  'Bike Repair',
  'Technology Assistance',
  'Computer Setup',
  'Lawn Care',
  'Spa Services',
  'Furniture Repair',
  'Office Setup',
  'HVAC Repair',
  'Sewing & Alterations',
  'Shoe Repair',
  'Car Detailing',
  'Catering',
  'Weddings & Events',
  'Fitness Coaching',
  'Life Coaching',
  'Virtual Assistant',
  'Tech Support',
  'Legal Consulting',
  'Business Consulting',
  'Financial Advice',
  'Marketing Services',
  'Web Development',
  'Content Writing',
  'Graphic Design',
  'Photography',
  'Social Media Management',
  'SEO Services',
  'Web Design',
  'App Development',
  'Video Editing',
  'Resume Writing',
  'Translation Services',
  'Bookkeeping',
  'Tax Preparation',
  'Speech Therapy',
  'Personal Chef',
  'Elder Care',
  'Nanny Services',
  'Transportation Services',
  'Delivery Services',
  'Landscaping',
  'Cleaning & Organizing',
  'Fitness Training',
  'Senior Care',
  'Yoga Instructor',
  'Therapist',
  'Counseling',
  'Chiropractor',
  'Nail Technician',
  'Massage Services',
  'Custom Gifts',
  'Pet Training',
  'House Painting',
  'Electrical Repairs',
  'Home Security Setup',
  'Holiday Decorating',
  'Christmas Lights Setup',
  'Home Improvement',
  'Smart Home Setup',
  'Carpentry',
  'Interior Design',
  'Piano Moving',
  'Office Cleaning',
  'Disability Support Services',
  'Pressure Washing',
  'Garage Cleaning',
  'Gutter Installation',
  'Tree Trimming',
  'Home Staging',
  'Tile Installation',
  'Wallpaper Installation',
  'Deck Repair',
  'Fence Installation',
  'Pool Installation',
  'House Renovations',
  'Deck Building',
  'Barbecue Assembly',
  'Furniture Moving',
  'Cement Work',
  'Fence Repair',
  'Woodwork',
  'Drywall Installation',
  'Wallpaper Removal',
  'Handyman Jobs',
  'Car Detailing',
  'Tattoo Artist',
  'Wedding Planner',
  'Party Planning',
  'Grooming Services',
  'House Cleaning',
  'Pool Repairs',
  
  // South Africa-specific services
  'Domestic Worker',
  'Nanny',
  'Security Guard',
  'Construction Worker',
  'Roadside Assistance',
  'House Painter',
  'Landscaping & Irrigation',
  'Boilermaker',
  'Plumbing and Gas Services',
  'Electric Fence Installation',
  'Pool Maintenance',
  'Seamstress',
  'Taxi Services',
  'Courier Services',
  'Gardening & Lawn Mowing',
  'Bricklayer',
  'Home Care Services',
  'Masonry Services',
  'Paving and Tiling',
  'Rubbish Removal',
  'Window Tinting',
  'Solar Panel Installation',
  'Pest Control Services',
  'Vehicle Services',
  'Home Security Systems',
  'Maid and Domestic Cleaning',
  'Welding Services',
  'Gutter Installation & Repair',
  'Fencing and Gate Installation',
  'Pool and Spa Services',
  'Lawn Mowing',
  'Household Renovations',
  'Recycling Services',
  'Gardener and Landscaper',
  'Tree Felling',
  'Catering for Events',
  'Moving Services',
  'Towing Services',
  'Property Maintenance',
  'General Handyman Services',
  'Housekeeping Services',
  'Event Security',
  'Party Services',
  'Civil Engineering Services',
  'Roofer',
  'Refrigeration Technician',
  'Carpentry & Joinery',
  'Commercial Cleaning',
  'Gardening Services',
  'Professional Drivers',
  'Mobile Car Wash'
  // Add more services as necessary
];

// API route for autocomplete
axios.get('/api/autocomplete', (req, res) => {
  const query = req.query.input.toLowerCase(); // Get the input query and convert it to lowercase
  const filteredServices = services.filter(service =>
    service.toLowerCase().includes(query) // Match the input with services in the list
  );

  res.json(filteredServices); // Send the filtered list of services as JSON response
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
